# Generated by Django 6.0 on 2025-12-16 12:00

import django.db.models.deletion
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('basic_income', 'Basic Income')], max_length=20)),
                ('salary_range', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_month', models.DateField(unique=True)),
                ('minimum_participants', models.IntegerField(default=5000)),
                ('current_participants', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('winners_selected', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-draw_month'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('region', models.CharField(choices=[('accra', 'Greater Accra Region'), ('ashanti', 'Ashanti Region'), ('eastern', 'Eastern Region'), ('central', 'Central Region'), ('western', 'Western Region'), ('volta', 'Volta Region'), ('other', 'Other Region')], max_length=20, verbose_name='Region in Ghana')),
                ('mobile_money_provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=20, verbose_name='Mobile Money Provider')),
                ('cv_file', models.FileField(upload_to='cv_files/', validators=[registrations.models.validate_cv_file], verbose_name='CV (PDF)')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=2)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_type', models.CharField(choices=[('job', 'Job Position'), ('basic_income', 'Basic Income')], max_length=20)),
                ('prize_details', models.TextField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('monthly_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.monthlydraw')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
            options={
                'unique_together': {('registration', 'monthly_draw')},
            },
        ),
    ]
